---
# Make sure all packages are up to date
- name: Update RPM-based systems
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  hosts: fedora
  tasks:
  - name: One
    dnf:
     name: "*"
     state: latest

- name: Update your DEB-based systems
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  hosts: debian
  tasks:
  - name: Two
    apt:
      name: '*'
      state: latest
      update_cache: yes